### ISSUE TITLE
Number of Dependents

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#44]
#2 >  #44

## Story

As a developer developer the application, I want a generic `NumberOfDependents` component, so that it can capture data in a contextualized environment.

## Details

Implement a `NumberOfDependents` component, this field will capture the data as is without validation or any other processing, note that there is a base `Autocomplete` #20   component that is required to complete this story.

In addition, this field will only implement the label attribute.

## Acceptance Criteria

- Project builds with no warning

## Definition of Done

- #4 

## Sub Task

* [ ] Project builds with no warning
* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Code peer-reviewed
* [ ] Storybook stories written
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

*  #2 

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

* #20
