### ISSUE TITLE
Field Context

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#77]
#24 > #77

## Story

As a developer developing the application, I want a react context name `FieldContext`, so that the component within the sub-three can be contextualized.

## Details

I'd like for you to implement a react context name `FieldContext`, and its corresponding `Provider` name `FieldContextProvider` this provider will allow the sub-three to consume at any level.

| Props | Description |
| ------ | ----------- |
| label | Field labels provide context and instructions for the information that should be entered. They make it clear what each input field represents. |
| name | field name refers to the identifier or name assigned to a specific data field or attribute |

## Acceptance Criteria

- Implement react context name `FieldContext`
- Implement context provider name `FieldContextProvider`

## Definition of Done

- #4 

## Sub Task

* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Code peer-reviewed
* [ ] Storybook stories written
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

- #24 

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

- None
