### ISSUE TITLE
Textarea

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#78]
#24 > #78

## Story

As a developer developing the application, I want a form textarea component named `Textarea` so that it can be used to capture data.

## Description 

A "textarea" is a user interface (UI) component that allows users to input and edit large or multiline text data within a form or application. It typically appears as a rectangular box or field on a user interface, where users can enter text content that may span multiple lines.

## Details

I'd like for you to implement a form textarea field component, this field will capture the input as is without validation or any other processing. 

In addition, this component should not accept any props instead it should derive the props from `FieldContext` #77.

## Acceptance Criteria

- Project builds with no warning

## Definition of Done

- #4 

## Sub Tasks

* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Storybook stories written
* [ ] Code peer-reviewed
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

- #24 

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

- #77

**Comment by iamshellyan** [comment]
@wycliffepeart Textarea? t your giving the form a name or is it just a place holder or something?

**Comment by wycliffepeart** [comment]
> @wycliffepeart Textarea? t your giving the form a name or is it just a place holder or something?

The textarea is a built-in element used by the browser. 

A <textarea> is an HTML element used to create a multi-line text input field in a web form. It allows users to enter and edit longer text, such as comments, descriptions, or other free-text content. The <textarea> element provides a larger text input area compared to a single-line text input field created with the <input> element.

**Comment by iamshellyan** [comment]
@wycliffepeart I added a description
