### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#80]
#24 > #80

## Story

As a developer developing the application, I want a form checkbox component named `Checkbox` so that it can be used to capture data.

## Description

A form checkbox is a common user interface (UI) element used in forms, applications, and websites. It consists of a small box that users can click or tap to toggle between two states: checked and unchecked.

## Details

I'd like for you to implement a form checkbox component, this field will capture the input as is without validation or any other processing. 

In addition, this component should not accept any props instead it should derive the props from `FieldContext` #77.

## Acceptance Criteria

- Project builds with no warning

## Definition of Done

- #4 

## Sub Tasks

* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Storybook stories written
* [ ] Code peer-reviewed
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

- #24 

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

- #77

**Comment by iamshellyan** [comment]
@wycliffepeart I added a description.
