### ISSUE TITLE
Path Context

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#84]
#24  > #84

## Story

As a developer developing the application, I want a react context name `PathContext`, so that the component within the sub-three can be contextualized.

## Details

I'd like for you to implement a react context name `PathContext`, and its corresponding `Provider` name `PathProvider` this provider will allow the sub-three to consume at any level.

| Props | Description |
| ------ | ----------- |
| Path | Path refers to the identifier or name assigned to a specific data field or attribute path within an object |

## Acceptance Criteria

- Implement react context name `PathContext`
- Implement context provider name `PathProvider`

## Definition of Done

- #4 

## Sub Task

* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Code peer-reviewed
* [ ] Storybook stories written
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

- #22

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

- None
