### ISSUE TITLE
Address: Country

### ISSUE THREAD

**Issue by wycliffepeart** [zendexa/project#92]
#2 >  #92

## Story

As a developer developer the application, I want a generic `AddressCountry` component, so that it can capture data in a contextualized environment.

## Details

Implement a `AddressCountry` component, this field will capture the data as is without validation or any other processing, note that there is a base `Country` #60  component that is required to complete this story.

In addition, this field will only implement the label attribute.

## Acceptance Criteria

- Project builds with no warning

## Definition of Done

- #4 

## Sub Task

* [ ] Project builds with no warning
* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Code peer-reviewed
* [ ] Storybook stories written
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

*  #2 

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

* #20
* #60

**Comment by iamshellyan** [comment]
@wycliffepeart what about proof of address, could it also be a component? there is a section on the form to click on the proof of address provided in the form of utility.

**Comment by wycliffepeart** [comment]
> @wycliffepeart what about proof of address, could it also be a component? there is a section on the form to click on the proof of address provided in the form of utility.

When we are developinng the document page we will consider the proof of address.
