### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by iamshellyan** [zendexa/project#93]
#24 #93

##Story 

As a developer developing the application, I want a generic `Date` component, so that it can capture data in a contextualized environment.

## Details

Implement a `Date` component, this field will capture the data as is without validation or any other processing, Note that there is a base `TextField` #18 component that is required to complete this story.

In addition, this field will only implement the label attribute.

## Acceptance Criteria

- Project builds with no warning

## Sub Task

* [ ] Project builds with no warning
* [ ] Unit tests written
* [ ] Integration test passing
* [ ] Code peer-reviewed
* [ ] Storybook stories written
* [ ] Tested on supported devices/browser
* [ ] Any configuration changes documented

## Linked issues

> **Relates to**
> Linking type that allows you to establish a relationship between two issues.

*  #24 

> **Blocked By**
> Issues or tasks that are blocking the progress of the issue.

* #18

**Comment by iamshellyan** [comment]
@wycliffepeart Kindly review and provide feedback.

**Comment by iamshellyan** [comment]
@wycliffepeart peart you have not provided any feedback.

**Comment by wycliffepeart** [comment]
@iamshellyan this is a duplicate look at #19 and refine it using this issue.

**Comment by iamshellyan** [comment]
@wycliffepeart the issue was already removed, your suggestion is acknowledged none the less thanks
